# Generated by Django 5.1.5 on 2025-04-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='image',
            new_name='distorted_image',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='fixed_image',
            field=models.ImageField(default=2024, upload_to='fixed_img/'),
            preserve_default=False,
        ),
    ]
