# Generated by Django 5.1.5 on 2025-04-07 05:43

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutus_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(help_text='home page content')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
