# Generated by Django 5.1.5 on 2025-04-07 05:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='home page content', null=True),
        ),
    ]
