# Generated by Django 5.1.5 on 2025-04-07 06:12

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_homepage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='home page content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Converter page content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cropper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Cropper page content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Resizer page content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Service page content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upscaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='home page content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
