# Generated by Django 5.1.5 on 2025-04-07 09:05

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_compressor_converter_cropper_resizer_servicepage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCompressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Image Compressor page content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageConverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Image Converter page content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageCropper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Imaage Cropper page content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageResizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Image Resizer page content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpscaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Upscale Image page content', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Compressor',
        ),
        migrations.DeleteModel(
            name='Converter',
        ),
        migrations.DeleteModel(
            name='Cropper',
        ),
        migrations.DeleteModel(
            name='Resizer',
        ),
        migrations.DeleteModel(
            name='Upscaler',
        ),
    ]
