# Generated by Django 5.1.5 on 2025-04-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedPageMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('search_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_canonical_page', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
